name: background_transfer
description: A Flutter plugin for handling background file transfers (uploads and downloads) with progress tracking and notifications support.
version: 1.0.0
homepage: https://github.com/Sylv3str3/flutter_background_file_transfer

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  path_provider: ^2.1.2
  path: ^1.8.3
  http: ^1.2.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.sylvestre.background_transfer
        pluginClass: BackgroundTransferPlugin
      ios:
        pluginClass: BackgroundTransferPlugin
